### ISSUE TITLE
Generalize methods to AbstractPolyhedron

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1078]
Follow-up of #780/#1077:

* [x] generalize `linear_map` to `AbstractPolyhedron` (#1093)
* [x] generalize `polyhedron` to `AbstractPolyhedron`
  This is also needed for the following refactorings:
  * [ ] generalize `isempty` to `AbstractPolyhedron`
  There are two optional implementations. The second one would just work. For the first one, we would need the `polyhedron` method above.
  * [ ] generalize `isempty` to list of constraints
  This allows to finish [this comment](https://github.com/JuliaReach/LazySets.jl/issues/780#issuecomment-456308999) by removing the `HPolyhedron` wrapper in [this line](https://github.com/JuliaReach/LazySets.jl/blob/master/src/is_intersection_empty.jl#L870).
* [x] replace `Union{AbstractPolytope, HPolyhedron}` by `AbstractPolyhedron` (#1501)
* [x] check which of the `AbstractPolytope` methods can be generalized
* [x] move the `Polyhedra` import code from `AbstractPolytope.jl` (#1501)
