### ISSUE TITLE
Add Zonotope section in the manual

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1294]
**Task.** Add a new section in the LazySets manual:

*Basic operations:*

- [ ] definition of a zonotope in R^n 
- [ ] construction and plot a 2D zonotope given center and generators
- [ ] construct a random zonotope
- [ ] plot 2D zonotopes of different order
- [ ] getter methods: dimension, center, matrix of generators
- [ ] obtain the H-representation
- [ ] example of the construction of a zonotope using line segments
- [ ] example of the M-sum of zonotopes which is again a zonotope
- [ ] example of the linear map of a zonotope
- [ ] example of enclosing axis-aligned box overapproximation
- [ ] example of the order reduction method available

*Other / for later:*

- [ ] example of the split method
- [ ] example of set membership
- [ ] example of containment check
- [ ] example of overapproximation of the convex hull of two zonotopes, using zonotopes of the same order and using zonotopes of different order
- [ ] example showing construction with dense matrix or with sparse matrix, and they are preserved under common operations
- [ ] example of the affine map of a zonotope
- [ ] cartesian product of two zonotopes (either 1D - 1D or 1D - 2D with Plots, requires #1260)
- [ ] example of the lazy intersection of zonotopes, overapproximation using template directions
- [ ] overapproximate a zonotope with a polytope in constraint representation  using template directions

*Not yet implemented:*

- [ ] some enclosure of polytopes with zonotopes methods vice-versa, cf. https://mediatum.ub.tum.de/doc/1287515/893367.pdf
- [ ] quadratic multiplication

CC: @aadesha
