### ISSUE TITLE
Roadmap: Documentation

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#14]
for "v1.0" we need to finish polishing the docs. on a high-level:

- [x] library of functions, include them all
- [x] beginning example: convex hull, M-sum, lazy mexp
- [x] finish "About" section
- [x] add a wiki page describing the documentation style that we use
   (we use it for `Reachability.jl` as well; eventually this will be unified for all repositories)
- [x] polyhedral approximations: resize figures and add text ssec 3
- [x] decomposing an affine map tutorial (from paper)
- [x] fast 2d LPs: resize fig and add Algorithm (from paper)
- [x] small examples for a "getting started" section, ~~use jupyter notebooks (?)~~ << we used `@examples` blocks
- [x] common set reps: review repeated docs of sigma << this is deferred to #72 
- [x] ~~add Polyhedra to the docs~~
- [x] clarify questions [here](https://github.com/JuliaReach/LazySets.jl/issues/14#issuecomment-348289126)

**Comment by schillic** [comment]
Can you elaborate which doc style we should follow?
[The Julia guidelines](https://docs.julialang.org/en/stable/manual/documentation/)?

I like that struct fields can be [commented in the code](https://docs.julialang.org/en/stable/manual/documentation/#Types-1).

**Comment by mforets** [comment]
> The Julia guidelines?

Yes, but i think that for headers (Input, Output, or Fields) should be three `###` because otherwise it displays as a huge title in the Jupyter Notebook. ATM we should have enough examples in this repo under `docs/src` and its subfolders.

> I like that struct fields can be commented in the code.

ok, i haven't tried this feature!

**Comment by mforets** [comment]
update: i've finished the `About` section of the documentation, adding some words about "Contributing", and slightly reformulated the new paragraph from @viryfrederic .

**Comment by schillic** [comment]
@mforets: We have to update the results of Julia code evaluations, e.g., [here](https://juliareach.github.io/LazySets.jl/latest/#Example-1).
I did not do it because we might want to check why we need more memory than before.

**Comment by schillic** [comment]
@mforets: Do we want to have rules for line breaks in the signatures?
Like "new line for every argument", "new line for return type"?

**Comment by mforets** [comment]
> Is it time to include doctests?

yes, this is a very good idea. i think we can put it in the milestone (to do after we get #14 merged)

**Comment by mforets** [comment]
> 1. We have to update the results of Julia code evaluations

OK, let me take care of updating that. also i can put it as a doctest. is there something for testing random outputs?

**Comment by schillic** [comment]
Let me do it.

**Comment by mforets** [comment]
> 2. Do we want to have rules for line breaks in the signatures?

i think that we shall have: "try to stay within 80 characters". apart from that, i'm not sure that we want to have a general rule, usually if the arguments fit in one line then it looks nice, but if there are many arguments it looks nicer if they are in different rows. this is subjective of course and also for this reason i don't advocate to a strict rule here.

**Comment by mforets** [comment]
> 3. Do we want to have a template for documenting type parameters?

does [the current info in the wiki](https://github.com/JuliaReach/LazySets.jl/wiki/Documentation-Guidelines#Documenting-types) qualify as such template?

> Do we want to require such documentation?

yes, i think this should be required

**Comment by mforets** [comment]
> 4. I find it more helpful to also see the return type in the docs.

agreed. then let's add the output type for `dim` in all LazySets types.

**Comment by schillic** [comment]
> > Do we want to have a template for documenting type parameters?
>
> does the current info in the wiki qualify as such template?

I do not think so. We see the type parameters in the first line, but there is no guide where to document the type parameters.

**Comment by mforets** [comment]
> 5. We should merge the sections on developing in about.md and getting_started.md (I forgot that we already had this). Where should we put it?

i feel like "development" doesn't fit in the "Getting Started" section. that was the reason to put it in the about.md otherwise, we can have a new section ["Contributing", as in documenter](https://juliadocs.github.io/Documenter.jl/stable/man/contributing/).

**Comment by schillic** [comment]
> > I find it more helpful to also see the return type in the docs.
>
> agreed. then let's add the output type for dim in all LazySets types.

Good, then I will add them.

**Comment by mforets** [comment]
> EDIT: What do you think about the return type Void for "no return value"? Is this helpful?

seems good since

```
julia> typeof(nothing)
Void
```

in those cases where nothing is returned we can as well say it in the `### Output` section

**Comment by mforets** [comment]
the function `unit_step` is a misnomer -- [this function](https://en.wikipedia.org/wiki/Heaviside_step_function) returns 0 for negative values of its argument. moreover its current docstring doesn't make sense:

```
    unit_step(x::Real)

The unit step function, which returns 1 iff x is greater than or equal to zero.
```

should we name it to `sign_right` to say that it is continuous from the right?

**Comment by mforets** [comment]
> 8.  If we copy the signature, is it still reasonable to write optional arguments in brackets?

i've added 2 examples to the wiki, in [this section](https://github.com/JuliaReach/LazySets.jl/wiki/Documentation-Guidelines#documenting-types-), what do you think?

**Comment by schillic** [comment]
Cool, I edited a bit. By the way, I found out how to write triple backticks in markdown code blocks: Just write the code blocks with quadruple backticks 🤕, like this:
`````
````julia
some text
```
text in triple backticks
```
after the backticks
````
`````
(Guess how I wrote this block 👀)

**Comment by schillic** [comment]
@mforets: Close?
