### ISSUE TITLE
Interface with Polyhedra.jl

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#155]
[Polyhedra.jl](https://github.com/JuliaPolyhedra/Polyhedra.jl) is a polyhedral computation interface and *concrete operations* with our `HPolytope` (and a `VPolytope`), such as: transformation between H and V reps, intersection and minkowski sum, are better handled through it as a dependency, see [representation](https://juliapolyhedra.github.io/Polyhedra.jl/latest/representation.html) and [utilities](https://juliapolyhedra.github.io/Polyhedra.jl/latest/utilities.html). Notice the additional advantage that the computations themselves are done with established libraries such as CDD.

---

These are fixes related the the `Polyhedra.jl` interface:

- [x] https://github.com/JuliaReach/LazySets.jl/issues/574
- [x] https://github.com/JuliaReach/LazySets.jl/issues/561
- [x] https://github.com/JuliaReach/LazySets.jl/issues/560
- [x] https://github.com/JuliaReach/LazySets.jl/issues/214
- [x] https://github.com/JuliaReach/LazySets.jl/issues/595

---

**Comment by schillic** [comment]
If we get the high loading times like we had for `Polyhedron` earlier, it would be cool if this could be kept optional. But I do not know how.
Plots.jl somehow manages to load backends dynamically.
Of course we can always comment the `include`.

**Comment by mforets** [comment]
ok i'll see. from what i saw before, if you don't use macros [Requires](https://github.com/MikeInnes/Requires.jl) is just fine.

**Comment by schillic** [comment]
You should not invest time into this. Feature first, optimization later 🐤

**Comment by mforets** [comment]
In #173 we added some functionality for converting from `Polyhedra` to `LazySets` objects. However there remain some loose ends. The utility operations  e.g. `convex_hull` or `intersection` are not necessarily associated to a representation (`HPolytope` or `VPolytope`). It may be preferable to move them to a new shared file `polyhedra_interface.jl`, or to a new module.

**Comment by mforets** [comment]
These are other fixes related the the `Polyhedra.jl` interface:

- [ ] https://github.com/JuliaReach/LazySets.jl/issues/574
- [ ] https://github.com/JuliaReach/LazySets.jl/issues/561
- [ ] https://github.com/JuliaReach/LazySets.jl/issues/560
- [ ] https://github.com/JuliaReach/LazySets.jl/issues/214
- [ ] https://github.com/JuliaReach/LazySets.jl/issues/595
