### ISSUE TITLE
Generalize convexity in docstrings of lazy operations

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1837]
If Bloating applies to non-convex sets as well, the docstring should be generalized.

Related to https://github.com/JuliaReach/LazySets.jl/issues/1838.

- [x] Affine map (#2629)
- [x] Bloating (#2630)
- [x] Cached Minkowski Sum Array (#2631)
- [x] CartesianProduct (#2636)
- [x] CartesianProductArray (#2638)
- [x] Complement (#2639)
- [x] ConvexHull (#2640)
- [x] ConvexHullArray (#2677)
- [x] ExponentialMap (#2681)
- [x] Intersection (#2683)
- [x] IntersectionArray (#2685)
- [x] InverseLinearMap (@schillic: nothing to do)
- [x] LinearMap (#2690)
- [x] MinkowskiSum (#2697)
- [x] MinkowskiSumArray (#2697)
- [x] Rectification (#2696)
- [x] ResetMap (#2695)
- [x] SymmetricIntervalHull (#2694)
- [x] Translation (#2693)
- [x] UnionSet (#2692)
- [x] UnionSetArray (#2691)
- [x] For lazy operations that preserve convexity: add this information to the docstrings. (#2698)

**Comment by schillic** [comment]
This applies to other lazy operations as well. Here is an example:

https://github.com/JuliaReach/LazySets.jl/blob/8f371b39480bf1251ee48c0b05c3594ad79643c6/src/LazyOperations/AffineMap.jl#L12-L21

**Comment by mforets** [comment]
OK, we can do these in the same issue. I added an item list in my first comment.

**Comment by schillic** [comment]
Currently subtypes of `LazySet` are convex. So these comments are correct in the current state and give you important information (namely that the operations preserve convexity). This information should be preserved in the documentation (possibly at a different place, e.g., under `### Notes`).
