### ISSUE TITLE
Extend LazySet to non-convex sets

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1895]
We plan to extend the `LazySet` interface to non-convex sets. Since this is a major breaking change, we will then release version 2 of this library.

For a smooth transition, we accept that code that used to receive a `LazySet` input before may continue to work for non-convex sets but the output is undefined (i.e., there may be an error, or there will be no error but the result may be inconsistent, or it may just work). We will gradually clarify these places, but the transition may happen before all places have been updated. Below we list the progress.

### not checked

* `ConcreteOperations/`
* `Interfaces/`

### checked

* `Approximations/`
* `Arrays/`
* `Assertions/`
* `Initialization/`
* `LazyOperations/` (#1837)
* `Plotting/`
* `Parallel/`
* `Sets/`
* `Utils/`
* single files (`convert.jl`, `init.jl`, `LazySets.jl`)

### to be discussed

* [x] `Plotting/mesh.jl`:
  We `@assert` that `constraints_list` is applicable. I think this method requires that the input is convex. So everything should be fine.
* [x] `Approximations/overapproximate.jl`:
  I think `overapproximate(cap::Intersection{N, <:LazySet, <:AbstractPolyhedron{N}}` should still work.

### to be changed

* [x] iterative refinement (#1855)
* [x] inclusion between line segment and lazy set (#1856)
* [x] docstrings of lazy operations (#1837)
* [ ] replace "convex set" by "set" in explanations of input parameters taking a `LazySet`
* [x] `convert.jl`: `convert(::Type{Interval}, S::LazySet{N})` only works for convex sets
* [x] `hausdorff_distance`
* [x] `underapproximate`
* [x] `overapproximate(::LazySet, Type{<:Interval})` returns `convert(Interval, S)`, which only works for convex sets (~~#1976~~)

**Comment by schillic** [comment]
> should there be also `NonConvexSet <: LazySet` ?

No, `ConvexSet` is already only a one-sided approximation ("definitely convex"). You cannot guarantee that a generally non-convex set is not accidentally convex. We may actually not have a use case for `ConvexSet` in the end (once we have replaced them all), but that is too far in the future.

**Comment by schillic** [comment]
Closing as superseded by #3047.
