### ISSUE TITLE
Specialized iterator methods `constraints` and `vertices`

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2264]
After merging #2263 we can add efficient methods.

Trivial cases:
* [ ] iterator with no element:
  * [ ] `constraints` for `Universe`
  * [ ] `vertices` for `EmptySet`
* [ ] iterator over a single element: `vertices` for `AbstractSingleton`
* [ ] iterator over a list:
  * [ ] `constraints` for `AbstractHPolygon`/`HPoly`
  * [ ] `vertices` for `VPolygon`/`VPolytope`

Non-exhaustive list of interesting cases:
* [ ] `AbstractHyperrectangle` (@schillic has a draft implementation)
