### ISSUE TITLE
Make ready for Julia v1.5

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2310]
[build log](https://travis-ci.org/github/JuliaReach/LazySets.jl/jobs/714930786)

* [x] The tests pass but there are warnings about global variables. (#2318)
* [x] The doctests fail because of a new output style for empty arrays. (#2504)
* [x] The [documentation of `isdisjoint`](https://github.com/JuliaReach/LazySets.jl/blob/bec8d2a4db6699262620ff359fabba70d255166a/src/ConcreteOperations/isdisjoint.jl#L54-L59) does not work. (#2504)
```julia
Warning: no docs found for 'isdisjoint' in `@docs` block in src/lib/binary_functions.md:23-46
```

**Comment by mforets** [comment]
>  The doctests fail because of a new output style for empty arrays.

in v1.5 it is 

```julia
julia> Vector{Vector{Float64}}()
Array{Float64,1}[]
```

and in v1.6 it is 

```julia
julia> Vector{Vector{Float64}}()
Vector{Float64}[]
```
