### ISSUE TITLE
Clean up plot_recipes

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#237]
* [x] Use plural form for vector plots (like `plot_zonotope`/`plot_zonotopes`).
* [x] Make the variable names consistent (sometimes we use `arr` for vectors, sometimes not).
* [x] Fix the first line of `plot_zonotope`'s documentation.
* [x] Unify the `plot_lazyset` methods with and without `ε`. This way we also use the `:scatter` option from above also in the `ε` case. (see #1304)
* [x] Use the `:scatter` option from above also in the vector case (currently it does not work).
* [x] Unify the `plot_polygon` methods with a `Union` (or better: `AbstractPolygon`).
* [x] Can we even use `AbstractPolytope` above? This way we could remove the plot recipes for zonotopes and would also get more efficient plotting methods for the other polytopic sets for free.
* [x] ~Use `NaN`s for vectors.~ (not needed)
* [x] Rename `plot_linesegment` for (vectors of) `Interval`s.
* [x] `@assert` that the dimensionality is 2.
* [x] colors are ignored for some plot recipes (e.g., `LineSegment`) (see #1304 and docstring extension)
* [x] plot of 1-vertex `VPolygon`/`VPolytope` should use `Singleton` plot recipe (maybe simplify? see #614)
* [x] plot of 2-vertex `VPolygon`/`VPolytope` should use `LineSegment` plot recipe (maybe simplify? see #614).
* [x] `seriestype := norm(vlist[1, :] - vlist[2, :]) ≈ 0 ? :scatter : :shape` seems to check if the first and the second vertex are very close, but what about a flat but long polygon? I think we should check for all vertices. This can also be useful for the previous item (flat polygons).

**Comment by schillic** [comment]
Also add the `NaN`s for vectors to get faster plots.

**Comment by mforets** [comment]
i think we can check `@assert that the dimensionality is 2.`

**Comment by schillic** [comment]
> i think we can check @assert that the dimensionality is 2.

The last six recipes do not check that.

**Comment by mforets** [comment]
we don't need to check for intervals and linesegments because they are 2d.

**Comment by schillic** [comment]
but for `Singleton`s

**Comment by mforets** [comment]
> colors are ignored for some plot recipes (e.g., LineSegment and Singleton)

For `Singleton`s, colors work here.

But for `LineSegment` colors don't work. One has to pass either `markercolor`, or `linecolor`, or both. The idea was that `linecolor` and `markercolor` are set to be the given `color`, but seems like it's not working.

**Comment by mforets** [comment]
> but for Singletons

ok we can add assertion on a singleton or a vector of singletons (both 2d and 3d can be plotted)

**Comment by schillic** [comment]
All items have been resolved :tada:

**Comment by mforets** [comment]
Nice :100:
