### ISSUE TITLE
Sparse Polynomial Zonotopes interface

### ISSUE THREAD

**Issue by lucaferranti** [JuliaReach/LazySets.jl#3018]
- [ ] Type and constructor #3015
- [ ] `dim` #3015
- [ ] `ngens` (two methods for dependent and independent generators and one for the total numbers) #3015
- [ ] `nparams` #3015
- [ ] `order` #3015
- [ ] `center` #3015
- [ ] `genmat` (similar to `ngens`) #3015
- [ ] `expmat` #3015
- [ ] `indexvector` #3015
- [ ] `linear_map` #3015
- [ ] `quadratic_map`
- [ ] `remove redundants`
- [ ] conversion Zonotope --> SPZ #3016
- [ ] conversion SSPZ --> SPZ #3016
- [ ] conversion SPZ --> SSPZ #3016
- [ ] conversion TaylorModels --> SPZ
- [ ] conversion SPZ --> TaylorModels
- [ ] conversion polytope --> SPZ
- [ ] zonotope overapproximation
- [ ] support function overapproximation
- [ ] polytope overapproximation
- [ ] ellipsoid overapproximation
- [ ] `plot`
- [ ] `minkowski_sum`
- [ ] `linear_combination`
- [ ] `convex_hull`
- [ ] `exact_sum`
- [ ] `cartesian_product`
- [ ] `uniqueID` #3016
- [ ] `mergeID`
- [ ] containment check SPZ ∈ SPZ
- [ ] containment check interval ∈ SPZ
- [ ] intersection check
- [ ] order reduction
- [ ] restructuring
- [ ] subset extraction
- [ ] splitting
