### ISSUE TITLE
Generalize ConvexSet to LazySet

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#3047]
This is a fresh start of #1895 because since then there have been changes. Now that there is `ConvexSet`, it is easy to keep track of the places that need to be generalized. The goal is to replace `ConvexSet` by `LazySet` whenever possible and, if convexity is assumed, think about a more general implementation.

A short road map:
- Generalize the concrete set types and interfaces. We have to keep the `<: ConvexSet` annotation of convex set types, at least for now for compatibility reasons (but I do not see a problem to permanently keep them). There are only three occurrences (apart from `ConvexSet.jl` of course), so this should be simple.
- Check the lazy operations (moderate amount of work). We have to keep the `<: ConvexSet` restrictions of the arguments and structs for now for compatibility reasons (see below).
- Define plot recipes for non-convex sets.
- Generalize the binary operations (lots of work).

When all of the above is done:
- Generalize the `ConvexSet` restrictions of lazy operations (both in the arguments and the structs).

---

### Rough suggested order

* [x] Sets/Ball1.jl ([#3050](https://github.com/JuliaReach/LazySets.jl/pull/3050))
* [x] Sets/Ball2.jl ([#3051](https://github.com/JuliaReach/LazySets.jl/pull/3051))
* [x] Sets/BallInf.jl ([#3063](https://github.com/JuliaReach/LazySets.jl/pull/3063))
* [x] Sets/Ballp.jl ([#3052](https://github.com/JuliaReach/LazySets.jl/pull/3052))
* [x] Sets/Ellipsoid.jl ([#3065](https://github.com/JuliaReach/LazySets.jl/pull/3065))
* [x] Sets/EmptySet.jl ([#3079](https://github.com/JuliaReach/LazySets.jl/pull/3079))
* [x] Sets/HalfSpace.jl ([#3081](https://github.com/JuliaReach/LazySets.jl/pull/3081))
* [x] Sets/HParallelotope.jl ([#3085](https://github.com/JuliaReach/LazySets.jl/pull/3085))
* [x] Sets/Hyperplane.jl ([#3090](https://github.com/JuliaReach/LazySets.jl/pull/3090))
* [x] Sets/Interval.jl ([#3084](https://github.com/JuliaReach/LazySets.jl/pull/3084))
* [x] Sets/Line.jl ([#3086](https://github.com/JuliaReach/LazySets.jl/pull/3086))
* [x] Sets/Line2D.jl ([#3088](https://github.com/JuliaReach/LazySets.jl/pull/3088))
* [x] Sets/LineSegment.jl ([#3089](https://github.com/JuliaReach/LazySets.jl/pull/3089))
* [x] Sets/RotatedHyperrectangle.jl ([#3091](https://github.com/JuliaReach/LazySets.jl/pull/3091))
* [x] Sets/Singleton.jl ([#3092](https://github.com/JuliaReach/LazySets.jl/pull/3092))
* [x] Sets/Universe.jl ([#3094](https://github.com/JuliaReach/LazySets.jl/pull/3094))
* [x] Sets/ZeroSet.jl ([#3093](https://github.com/JuliaReach/LazySets.jl/pull/3093))
* [x] Sets/Hyperrectangle.jl ([#3095](https://github.com/JuliaReach/LazySets.jl/pull/3095))
* [x] Sets/Star.jl ([#3096](https://github.com/JuliaReach/LazySets.jl/pull/3096))
* [x] Sets/Zonotope.jl ([#3071](https://github.com/JuliaReach/LazySets.jl/pull/3071), [#3097](https://github.com/JuliaReach/LazySets.jl/pull/3097))
* [x] Sets/VPolygon.jl ([#3106](https://github.com/JuliaReach/LazySets.jl/pull/3106))
* [x] Sets/VPolytope.jl ([#3107](https://github.com/JuliaReach/LazySets.jl/pull/3107))
* [x] Sets/HPolytope.jl ([#3102](https://github.com/JuliaReach/LazySets.jl/pull/3102))
* [x] Sets/HPolyhedron.jl ([#3162](https://github.com/JuliaReach/LazySets.jl/pull/3162))
* [x] Sets/HPolygon.jl ([#3164](https://github.com/JuliaReach/LazySets.jl/pull/3164))
* [x] Sets/HPolygonOpt.jl ([#3164](https://github.com/JuliaReach/LazySets.jl/pull/3164))
* [x] Sets/DensePolynomialZonotope.jl ([#3166](https://github.com/JuliaReach/LazySets.jl/pull/3166))
* [x] Sets/SimpleSparsePolynomialZonotope.jl ([#3167](https://github.com/JuliaReach/LazySets.jl/pull/3167))
* [x] Sets/SparsePolynomialZonotope.jl ([#3190](https://github.com/JuliaReach/LazySets.jl/pull/3190))
* [x] Initialization (init_Polyhedra.jl & init_Javis.jl) ([#3098](https://github.com/JuliaReach/LazySets.jl/pull/3098))
* [x] Utils/samples.jl ([#3100](https://github.com/JuliaReach/LazySets.jl/pull/3100))
* [x] Utils/helper_functions.jl ([#3110](https://github.com/JuliaReach/LazySets.jl/pull/3110))
* [x] Utils/macros.jl ([#3165](https://github.com/JuliaReach/LazySets.jl/pull/3165), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] Parallel ([#3112](https://github.com/JuliaReach/LazySets.jl/pull/3112))
* [x] Plotting/mesh.jl ([#3114](https://github.com/JuliaReach/LazySets.jl/pull/3114))
* [x] Plotting/paraview.jl ([#3113](https://github.com/JuliaReach/LazySets.jl/pull/3113))
* [x] Plotting/plot_recipes.jl ([#3127](https://github.com/JuliaReach/LazySets.jl/pull/3127), [#3139](https://github.com/JuliaReach/LazySets.jl/pull/3139))
* [x] Approximations/ballinf_approximation.jl ([#3118](https://github.com/JuliaReach/LazySets.jl/pull/3118))
* [x] Approximations/box_approximation.jl ([#3072](https://github.com/JuliaReach/LazySets.jl/pull/3072), [#3118](https://github.com/JuliaReach/LazySets.jl/pull/3118))
* [x] Approximations/overapproximate_interval.jl ([#3075](https://github.com/JuliaReach/LazySets.jl/pull/3075))
* [x] Approximations/symmetric_interval_hull.jl ([#3118](https://github.com/JuliaReach/LazySets.jl/pull/3118))
* [x] Approximations/approximate.jl ([#3119](https://github.com/JuliaReach/LazySets.jl/pull/3119))
* [x] Approximations/Approximations.jl ([#3119](https://github.com/JuliaReach/LazySets.jl/pull/3119))
* [x] Approximations/hausdorff_distance.jl ([#3119](https://github.com/JuliaReach/LazySets.jl/pull/3119))
* [x] Approximations/init_Ipopt.jl ([#3119](https://github.com/JuliaReach/LazySets.jl/pull/3119))
* [x] Approximations/underapproximate.jl ([#3119](https://github.com/JuliaReach/LazySets.jl/pull/3119))
* [x] Approximations/iterative_refinement.jl ([#3121](https://github.com/JuliaReach/LazySets.jl/pull/3121))
* [x] Approximations/template_directions.jl ([#3122](https://github.com/JuliaReach/LazySets.jl/pull/3122))
* [x] Approximations/overapproximate.jl ([#3075](https://github.com/JuliaReach/LazySets.jl/pull/3075), [#3140](https://github.com/JuliaReach/LazySets.jl/pull/3140))
* [x] Approximations/decompositions.jl ([#3128](https://github.com/JuliaReach/LazySets.jl/pull/3128), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] ConcreteOperations/distance.jl ([#3129](https://github.com/JuliaReach/LazySets.jl/pull/3129))
* [x] ConcreteOperations/exact_sum.jl ([#3130](https://github.com/JuliaReach/LazySets.jl/pull/3130))
* [x] ConcreteOperations/isstrictsubset.jl ([#3131](https://github.com/JuliaReach/LazySets.jl/pull/3131))
* [x] ConcreteOperations/linear_combination.jl ([#3132](https://github.com/JuliaReach/LazySets.jl/pull/3132))
* [x] ConcreteOperations/minkowski_difference.jl ([#3133](https://github.com/JuliaReach/LazySets.jl/pull/3133))
* [x] ConcreteOperations/difference.jl ([#3134](https://github.com/JuliaReach/LazySets.jl/pull/3134))
* [x] ConcreteOperations/cartesian_product.jl ([#3135](https://github.com/JuliaReach/LazySets.jl/pull/3135))
* [x] ConcreteOperations/minkowski_sum.jl ([#3145](https://github.com/JuliaReach/LazySets.jl/pull/3145))
* [x] ConcreteOperations/intersection.jl ([#3147](https://github.com/JuliaReach/LazySets.jl/pull/3147))
* [x] ConcreteOperations/convex_hull.jl ([#3148](https://github.com/JuliaReach/LazySets.jl/pull/3148))
* [x] ConcreteOperations/issubset.jl ([#3154](https://github.com/JuliaReach/LazySets.jl/pull/3154))
* [x] ConcreteOperations/isdisjoint.jl ([#3156](https://github.com/JuliaReach/LazySets.jl/pull/3156))
* [x] convert.jl ([#3159](https://github.com/JuliaReach/LazySets.jl/pull/3159))
* [x] ~Interfaces/AbstractArraySet.jl~
* [x] Interfaces/AbstractStar.jl ([#3109](https://github.com/JuliaReach/LazySets.jl/pull/3109))
* [x] Interfaces/AbstractPolynomialZonotope.jl ([#3109](https://github.com/JuliaReach/LazySets.jl/pull/3109))
* [x] Interfaces/aliases.jl ([#3142](https://github.com/JuliaReach/LazySets.jl/pull/3142))
* [x] Interfaces/AbstractSingleton.jl ([#3143](https://github.com/JuliaReach/LazySets.jl/pull/3143))
* [x] Interfaces/AbstractPolytope.jl ([#3144](https://github.com/JuliaReach/LazySets.jl/pull/3144))
* [x] Interfaces/LazySet.jl ([#3149](https://github.com/JuliaReach/LazySets.jl/pull/3149))
* [x] Interfaces/AbstractPolyhedron.jl ([#3150](https://github.com/JuliaReach/LazySets.jl/pull/3150))
* [x] Interfaces/AbstractPolygon.jl ([#3151](https://github.com/JuliaReach/LazySets.jl/pull/3151))
* [x] Interfaces/AbstractCentrallySymmetric.jl ([#3152](https://github.com/JuliaReach/LazySets.jl/pull/3152))
* [x] Interfaces/AbstractCentrallySymmetricPolytope.jl ([#3153](https://github.com/JuliaReach/LazySets.jl/pull/3153))
* [x] Interfaces/AbstractHyperrectangle.jl ([#3157](https://github.com/JuliaReach/LazySets.jl/pull/3157))
* [x] Interfaces/AbstractPolyhedron_functions.jl ([#3161](https://github.com/JuliaReach/LazySets.jl/pull/3161))
* [x] Interfaces/AbstractHPolygon.jl ([#3164](https://github.com/JuliaReach/LazySets.jl/pull/3164))
* [x] Interfaces/AbstractZonotope.jl ([#3191](https://github.com/JuliaReach/LazySets.jl/pull/3191))
* [x] Interfaces/AbstractAffineMap.jl ([#3163](https://github.com/JuliaReach/LazySets.jl/pull/3163), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195)..)
* [x] Interfaces/ConvexSet.jl ([#3074](https://github.com/JuliaReach/LazySets.jl/pull/3074), [#3185](https://github.com/JuliaReach/LazySets.jl/pull/3185))
* [x] LazyOperations/QuadraticMap.jl ([#3099](https://github.com/JuliaReach/LazySets.jl/pull/3099))
* [x] LazyOperations/Complement.jl ([#3104](https://github.com/JuliaReach/LazySets.jl/pull/3104))
* [x] LazyOperations/ConvexHull.jl ([#3177](https://github.com/JuliaReach/LazySets.jl/pull/3177))
* [x] LazyOperations/ConvexHullArray.jl ([#3172](https://github.com/JuliaReach/LazySets.jl/pull/3172))
* [x] LazyOperations/QuadraticMap.jl ([#3182](https://github.com/JuliaReach/LazySets.jl/pull/3182))
* [x] LazyOperations/Rectification.jl ([#3192](https://github.com/JuliaReach/LazySets.jl/pull/3192))
* [x] LazyOperations/SymmetricIntervalHull.jl ([#3187](https://github.com/JuliaReach/LazySets.jl/pull/3187))
* [x] LazyOperations/UnionSet.jl ([#3180](https://github.com/JuliaReach/LazySets.jl/pull/3180))
* [x] LazyOperations/UnionSetArray.jl ([#3175](https://github.com/JuliaReach/LazySets.jl/pull/3175))
* [x] LazyOperations/AffineMap.jl ([#3168](https://github.com/JuliaReach/LazySets.jl/pull/3168), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/Bloating.jl ([#3103](https://github.com/JuliaReach/LazySets.jl/pull/3103), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/CachedMinkowskiSumArray.jl ([#3170](https://github.com/JuliaReach/LazySets.jl/pull/3170), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/CartesianProduct.jl ([#3176](https://github.com/JuliaReach/LazySets.jl/pull/3176), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/CartesianProductArray.jl ([#3171](https://github.com/JuliaReach/LazySets.jl/pull/3171), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/ExponentialMap.jl ([#3189](https://github.com/JuliaReach/LazySets.jl/pull/3189), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/Intersection.jl ([#3178](https://github.com/JuliaReach/LazySets.jl/pull/3178), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/IntersectionArray.jl ([#3173](https://github.com/JuliaReach/LazySets.jl/pull/3173), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/InverseLinearMap.jl ([#3181](https://github.com/JuliaReach/LazySets.jl/pull/3181), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/LinearMap.jl ([#3188](https://github.com/JuliaReach/LazySets.jl/pull/3188), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/MinkowskiSum.jl ([#3179](https://github.com/JuliaReach/LazySets.jl/pull/3179), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/MinkowskiSumArray.jl ([#3174](https://github.com/JuliaReach/LazySets.jl/pull/3174), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/ResetMap.jl ([#3183](https://github.com/JuliaReach/LazySets.jl/pull/3183), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
* [x] LazyOperations/Translation.jl ([#3184](https://github.com/JuliaReach/LazySets.jl/pull/3184), [#3195](https://github.com/JuliaReach/LazySets.jl/pull/3195))
